# Generated by Django 5.0.6 on 2026-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_attendance_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
